"""add_scheduling_mode_and_periods_to_org

Revision ID: 0591f3e6ceec
Revises: adb25646ab8d
Create Date: 2026-06-25 18:59:02.919089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0591f3e6ceec'
down_revision: Union[str, None] = 'adb25646ab8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('scheduling_mode', sa.String(), server_default='fixed_weekday', nullable=False))
    op.add_column('organizations', sa.Column('cycle_length', sa.Integer(), server_default='6', nullable=False))
    op.add_column('organizations', sa.Column('periods_per_day', sa.Integer(), server_default='5', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'periods_per_day')
    op.drop_column('organizations', 'cycle_length')
    op.drop_column('organizations', 'scheduling_mode')
    # ### end Alembic commands ###
